spring.datasource.url=jdbc:sqlserver://NICHOLAS:1433;databaseName=Kpop;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

paypal.client.id=BAAZoqSiSYSpfor_0EKMS5HcdPTbGWyPh7cmxdjG2minkKeOdIHcj5iilufkBO1EZCGgLUfr2ErJ9E8GbQ
paypal.client.secret=EJylhvgVROGFp5RIMSMQPzQbIDi_cRQieL8UvLf0F3HawVSfmETbfzEZXTq44-uyka_AzwlbaglzMMLz

jwt.secret=kpop-local-dev-secret-key-2026-change-me-please