spring.application.name=kpopbackend

spring.config.import=optional:classpath:application-secret.properties

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

paypal.mode=sandbox
paypal.currency=MYR
paypal.return-url=http://localhost:3000/payment-success
paypal.cancel-url=http://localhost:3000/payment-cancel

jwt.expiration-ms=86400000